// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vteupoqnwlybyaasgcqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0ZXVwb3Fud2x5YnlhYXNnY3FtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MDIzNDQsImV4cCI6MjA1ODk3ODM0NH0.nHSvfJMHjJifvICjawyODKERk7DXl7OZW6T7DXSpmd8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);